### ISSUE TITLE
Clean up RDAP data

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/stdlib-source#190]
# Issues

## DecodeData

Everything seems to have a `DecodeData` field which is empty. We should see if we can change the `ToAttributes` function to remove these e.g.

```yaml
links:
- DecodeData: {}
  Href: https://rdap.arin.net/registry/autnum/19425
  Rel: self
  Type: application/rdap+json
  Value: https://rdap.arin.net/registry/autnum/19425
- DecodeData: {}
  Href: https://whois.arin.net/rest/asn/AS19425
  Rel: alternate
  Type: application/xml
  Value: https://rdap.arin.net/registry/autnum/19425
```

## Vcard

We can definitely parse any vCard data into a much better format

## Entites

Some entities still contains the details of their linked entities, we should remove this as the data will be shown in the graph

## Autnums

Entities still include autnum details which should also be stripped as this will be included in the graph itself

## Networks

Entities also include network details, this should be stripped

## Links

These are probably the most abundant thing that gets returned, and they are very ugly. Removing the `DecodeData` section will help, but they are still pretty ugly... Not sure what to do about it without losing potentially useful data though

# Work Tracking

* [x] `DecodeData`
* [x] `Vcard`
* [x] `Entites`
* [x] `Autnums`
* [x] `Networks`
* [x] `Links`
